### ISSUE TITLE
Sugestões para o seu último post

### ISSUE THREAD

**Issue by leonardosouza** [mathvbarone/mathvbarone.github.io#1]
Fala @mathvbarone, algumas sugestões pro seu post:

No primeiro exemplo:

`(() => {
        // DECLARANDO AS VARIÁVEIS REFERENTES À INTERFACE
        const container = document.querySelector(".container");
        const form = document.querySelector(".form");
        const fields = document.querySelectorAll(".input-field");
        const nameInput = document.getElementById("name");
        const emailInput = document.getElementById("email");
        const messageInput = document.getElementById("message");
        const submitButton = document.getElementById("submit-button");
    })();`

Você não acha melhor usar o `.querySelector()` em vez do `getElementById()`?

====

Neste trecho:

`    validateField(nameRegexp, nameInput);
    validateField(emailRegexp, emailInput);
    validateField(msgRegexp, messageInput);`

Um `forEach` aqui para atribuir dinamicamente o regex e o campo seria uma boa não, ao invés de chamar a função `validateField` 3 vezes!

====

E aqui:

` fields.forEach((field) => {
            field.addEventListener("input", validateForm);
        });
        submitButton.addEventListener("click", (evnt) => {
            evnt.preventDefault();
        });`

Acho que dá pra simplificar e resolver tudo numa linha não!? Exemplo:

`fields.forEach(field => field.addEventListener("input", validateForm))`

=====

Pra fechar, eu sugiro também que você vá aplicando o código gradualmente, mais mantendo a base... pq senão fica confuso pro leitor entender onde cada coisa vai se encaixar!

Bom acho que é isso! ;-)

**Comment by mathvbarone** [comment]
Fala @leonardosouza !

Com certeza  são argumentos válidos que vou implementar dentro do tutorial!

Obrigado pelo feedback!

**Comment by mathvbarone** [comment]
Eu só não entendi muito bem como executar essa parte:

> Neste trecho:
> 
> validateField(nameRegexp, nameInput); validateField(emailRegexp, emailInput); validateField(msgRegexp, messageInput);
> 
> Um forEach aqui para atribuir dinamicamente o regex e o campo seria uma boa não, ao invés de chamar a função validateField 3 vezes!

Seria: 
```
validateField.forEach( function => {
     function(regExp, field);
} );
```

?

**Comment by leonardosouza** [comment]
Faz um array de objetos e itera:

`[ { regex: nameRegexp, field: nameInput}, { regex: emailRegexp, field: emailInput }, { regex: msgRegexp, field: messageInput } ].forEach(o => validateField(o.regex, o.field))`

**Comment by mathvbarone** [comment]
Boa!!

Não tinha pensado nisso.

Vou implementar, valeu :D
